### ISSUE TITLE
Word wrap does not work as I expected

### ISSUE THREAD

**Issue by StewBC** [stefan-b-jakobsson/x16-edit#15]
1st off - nice work 👍 

1) When word wrap is turned on, and there's a line that goes past the word wrap col, it will not re-wrap (instantly, when word wrap is turned on, as I expected).
1) When setting a word wrap at say 80 columns, after the cursor is past 80 col, the line will not break when typing more. (Adding #1 behaviour fixes this as well).
3) When putting the cursor on a long line, before the word wrap col, the text to the right of the cursor will not wrap when it goes past the word wrap col.  Only when the cursor gets to the word wrap col does the word wrap happen.

It's possible that my desire of word wrap (hard, whole document) is not the intended behavour.  In that case, I think there should be an option (and I didn't see it in the help) to re-wrap all text to the selected word wrap column.

**Comment by stefan-b-jakobsson** [comment]
Hello StewBC.

The word wrap feature is, as described in more detail in the user manual, very rudimentary. Currently it works just as you describe.

I would also prefer a less rudimentary solution. Making it better is, however, not trivial. I have to think about it to see what may be done with reasonable effort.

**Comment by stefan-b-jakobsson** [comment]
Version 0.3.5 supports a justify text buffer command.

I'm closing this issue now.
