### ISSUE TITLE
I can not get x16-edit to compile

### ISSUE THREAD

**Issue by edrahn01** [stefan-b-jakobsson/x16-edit#16]
I get these errors when compiling:

Unresolved external '__VARS_LOAD__' referenced in:
  /home/ed/X16/x16-edit/build/../ram.inc(99)
  /home/ed/X16/x16-edit/build/../ram.inc(40)
Unresolved external '__ZEROPAGE_LOAD__' referenced in:
  /home/ed/X16/x16-edit/build/../ram.inc(103)
  /home/ed/X16/x16-edit/build/../ram.inc(44)
ld65: Error: 2 unresolved external(s) found - cannot create output file

**Comment by stefan-b-jakobsson** [comment]
Hard to say.

Which build script were you running? What OS do you use?

I tried myself to download the master branch from Github, so it would not be affected by any other state in my local development folder. 

I could run build-ram.sh successfully. 

I noticed that there is an unresolved error in the code affecting the build-rom.sh, so you cannot at the moment build this target from the master branch. I will fix it later today. But that dosen't help your problem.

VARS_LOAD and ZEROPAGE_LOAD are set by the assembler/linker from the cx16-asm.cfg file (the "define" option).

A first step would be to make sure that the problem isn't the build script not working on your OS. I have only tested the build script on MacOS myself. 

Try compile from the command line instead:

`cl65 -v --asm-args -Dtarget_mem=1 -o X16EDIT.PRG -u __EXEHDR__ -t cx16 -C cx16-asm.cfg -vm ../main.asm`

If nothing else works, you can hard code the addresses in ram.inc as follows:

- Delete or comment out line 20: 
`;.import __ZEROPAGE_LOAD__, __ZEROPAGE_SIZE__, __VARS_LOAD__`

- Insert a two new lines after that:
`__ZEROPAGE_LOAD__ = $22`
`__VARS_LOAD__ = $0400`

**Comment by edrahn01** [comment]
Thank you.
