### ISSUE TITLE
Ctrl-R to Open File clashes with Reset on x16-emulator

### ISSUE THREAD

**Issue by csorian** [stefan-b-jakobsson/x16-edit#17]
In x16-edit pressing Ctrl-R is shown as mapped to Open File.  However, in the x16-emulator Ctrl-R is trapped to reset the emulator.

**Comment by stefan-b-jakobsson** [comment]
Hi!

Yes, I'm aware that Ctrl+R is treated as reset by the emulator on Windows and Linux, but not on MacOS. On the forum at commanderx16.com, it has been proposed to remove the emulator keyboard shortcuts, replacing them with buttons or menu items in the GUI. I think this would be the proper way of solving the issue.

On the real hardware this should not be a problem.

In the meantime you may use one of the alternative methods of accessing open file:

- Press and release ESC followed by R
- F4, will in the next release by changed to F5

**Comment by csorian** [comment]
Thank you for the advice and update. I'll use the alternative methods available for now. Thank you.
