### ISSUE TITLE
doesn't deal with/reset non-default screenmodes

### ISSUE THREAD

**Issue by irmen** [stefan-b-jakobsson/x16-edit#19]
When the x16's screen mode is not the default 80x50 characters, it's not reset / or x16edit doesn't adjust for it.
This means the bottom half of the screen is invisible.

Likewise for other screen resolutions, which are easy to set on the recent kernals with SCREEN 1-6

It would be nice if at least the 80x25 mode (double height characters) is supported, as I tend to find that easier to read on large texts.
But I guess resetting the screen to be 80x50 again is also an option.

**Comment by stefan-b-jakobsson** [comment]
Ensuring the default 80x60 should be easy. I will fix that for now.

Supporting other screen modes is certainly possible, but would require a lot more work, as X16 Edit was not written with this in mind.

**Comment by stefan-b-jakobsson** [comment]
Screen modes are handled like this for now:

- The editor support one screen mode that is set on startup
- If you compile the editor yourself, you may select the screen mode you like in the source file common.inc, just change the value of SCREEN_TEXTMODE

The editor is made for 80x60.

80x30 will look pretty OK.

In 40x30 or less there will be overlaps in the interface. Still usable, but not very nice looking.
