### ISSUE TITLE
crashes when trying to show next page of file listing

### ISSUE THREAD

**Issue by irmen** [stefan-b-jakobsson/x16-edit#20]
when loading/saving a file I can call up a list of the files on disk.
when attempting to go to the next page with ctrl-v, x16edit crashes.

**Comment by stefan-b-jakobsson** [comment]
I couldn't reproduce this bug.

Tested with master branch, 0.5.1 and 0.5.0 in emulator R41.

Can you give some more info on the circumstances when this happened.

**Comment by irmen** [comment]
1. load x16edit.prg 0.5.1 and run it
2. ctrl-O to write file
3. ctrl-T to list directory
4. it shows about 40 or so files and 'more'
5. press ctrl-V 'next page' 
6. crashes into monitor.

my sdcard contains around 70 files.

**Comment by irmen** [comment]
[sdcard.zip](https://github.com/stefan-b-jakobsson/x16-edit/files/9115512/sdcard.zip)

here is the sd card image that triggers the problem. please delete this comment once you downloaded it

**Comment by stefan-b-jakobsson** [comment]
I tested your SD card file, it still didn't crash.

I'm using MacOS + Emulator R41.

**Comment by irmen** [comment]
Well, that is extremely odd.  Maybe someone else can check?

I'm using latest Emulator and roms built from git master branches (both box16 and x16emu show the same problem).  I don't believe the operating system is a factor here, but for what it's worth, I'm on Manjaro Linux.
Re-testing it with the official R41 released emulator + rom, still crashes.

Could it be that my cc65 has a bug in it so that my build of x16edit.prg is faulty in a subtle way? edit: no, the prg downloaded from the x16 forum also has the same problem.

*edit* might have something to do with the fact that CTRL+V is "paste clipboard" and that this sends a stream of characters to the editor that it doesn't like? Look at the crash screen I get:
![image](https://user-images.githubusercontent.com/1771820/179214059-4acef410-2d9f-4cf0-a19b-da39945f4c5d.png)
that line that is pasted there is what I happened to have selected on my clipboard.
Too bad the ESC+V alternative doesn't work in this screen.

**Comment by stefan-b-jakobsson** [comment]
I think I have found the bug in file keyboard.inc.

In the function keyboard_mode_file_dir the program stepped through a list of key values. If no match was found it still falled through after line 678 ("bcc loop") to the following code that made the program jmp to an invalid address.

I could make the program crash on MacOS too by pressing for instance Ctrl+S (not a valid keystroke in this context).

Please confirm that it works for you.

**Comment by irmen** [comment]
Yup, it no longer crashes. Thanks.

I do still think it's a good idea to see a hint on screen that PgUp/PgDwn also scroll the pages, not only ctrl/y/v ?
