### ISSUE TITLE
Program crashes as soon as Ctrl-R is hit

### ISSUE THREAD

**Issue by jestin** [stefan-b-jakobsson/x16-edit#21]
When trying to open a file from the official emulator, Ctrl-R just crashes the application.  The command line used to run was `x16emu -sdcard card.img -prg X16EDIT-0.5.3.PRG -run -scale 2 -gif open_bug.gif` and the SD image is valid.  Here's a gif of the crash:
![open_bug](https://user-images.githubusercontent.com/669174/190942541-c02bb4ad-2dc8-4019-8f67-6e9b65dee42d.gif)

**Comment by jestin** [comment]
Disregard.  I've been informed that CTL-R is picked up by the emulator and forces a reset.  I would, however, recommend adding a note about that on the Commander X16 forum page where the project is listed: https://www.commanderx16.com/forum/index.php?/files/file/68-x16-edit-a-text-editor/

**Comment by stefan-b-jakobsson** [comment]
Thanks. I updated the instructions on the Commander X16 download page. Closing this this issue.
