### ISSUE TITLE
extra M on the first column on the first row (assuming left over ^M)

### ISSUE THREAD

**Issue by voidstar78** [stefan-b-jakobsson/x16-edit#24]
While creating TEXT files with notepad++ under Windows, I then opened them with X16EDIT on the X16 system.
For each file, I noticed an extra "M" on the first row of text (and only on that first row).
I figure this is a left over from a ^M (new line) in handling of the CRLF stuff (i.e. it probably tries to auto-detect this, and has a little hiccup about it on the very first line of parsing).

This only happens on the first line, no extra "M"'s appear on subsequent lines.

**Comment by voidstar78** [comment]
Here is an example

Note: I now think the problem is only if the first line happens to be blank.    [ makes sense, maybe it doesn't know yet; and the assumption is incorrect on that first line ]

[SAMPLE2.TXT](https://github.com/stefan-b-jakobsson/x16-edit/files/12911879/SAMPLE2.TXT)

**Comment by stefan-b-jakobsson** [comment]
I committed code that should fix this to the master branch
